version: "3.4"
services:
  ddl: #docker run -it -v ${PWD}:/work -w /work -p 5003:5000 aimvector/python:1.0.0 /bin/sh
    container_name: docker-deep-learning
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    build:
      context: ./
      target: debug
    #working_dir: /work      #comment out for build.target:prod
    #entrypoint: /bin/sh     #comment out for build.target:prod
    stdin_open: true # uncomment this if you want everything you print() to appear in the terminal where you run 'docker-compose up'
    tty: true #comment out for build.target:prod
    volumes:
      - ./src/:/work
    ports:
      - 5678:5678
