version: "3.8"
services:
  ddl:
    container_name: docker-deep-learning-debug
    # The following lines define the NVIDIA runtime and give the container access to all available GPU devices on the host.
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # The context used when building the image.
    # In this case it is the project's root, where the docker-compose build command is executed from
    build:
      context: ./
    # 
    stdin_open: true
    tty: true
    # Here we mount the ./src directory containing our code from the host machine into the container.
    # This way, our container always gets the most up-to-date state of our code base, without needing to rebuild the image! :)
    volumes:
      - ./src/:/work
    # This forwards the container port 5678 to host port 5678, where we wil start the debugger from within VSCode.
    ports:
      - 5678:5678       
